feature_engineering:
  vectorizer: tfidf_vectorizer
  max_features: 3200
  min_df: 3
  ngrams:
    min: 1
    max: 1

model_training:
  model_name: XGB-v3
  hyperparameters:
    n_estimators: 550
    learning_rate: 0.1
    max_depth: 6
    tree_method: hist
    max_bin: 128
    scale_pos_weight: 1.15
    gamma: null
    reg_lambda: 1
    subsample: 0.8
    colsample_bytree: 0.7

model_evaluation:
  threshold: 0.48
